---
title: "week51: 14.12.2021"
output: github_document
---

```{r}
library(tidyverse)
library(ggplot2)
library(ggtext)
library(tidytuesdayR)
library(scales)
library(ggrepel)
theme_set(theme_light())

```


```{r}
# tuesdata <- tidytuesdayR::tt_load(2021, week = 51)
tuesdata <- tidytuesdayR::tt_load('2021-12-14')
```


```{r, dataframes}
lyrics<- data.frame(tuesdata$lyrics)
related<- data.frame(tuesdata$related_artists)
songs<- data.frame(tuesdata$songs)
```


```{r}

related0 <-related %>% 
  group_by(genres) %>% 
  summarize(total = sum(followers_total)) %>% 
  arrange(desc(total))


related_df <-related %>% 
  filter(genres == 'dance pop') %>% 
  group_by(artist_name) %>% 
  summarize(total = sum(followers_total)) %>% 
  arrange(desc(total))

related_df %>% 
  slice(c(1:10, (n()-10):n())) %>% 
  #mutate(Artist =fct_reorder(artist_name,total)) %>% 
  mutate(Artist=artist_name) %>% 
  ggplot(aes(total, Artist, size=total, color = total))+
    geom_point(aes(alpha=.5))+
  labs( x=" # followers",
        title = "What are the bands that shaped women band trends?")+
  theme(legend.position = "none",
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank()) +
    geom_text_repel(
    aes(label = Artist),
    family = "Poppins",
    size = 3,
    min.segment.length = 0, 
    seed = 42, 
    box.padding = 0.5,
    max.overlaps = Inf,
    arrow = arrow(length = unit(0.010, "npc")),
    nudge_x = .15,
    nudge_y = .5,
    color = "grey50"
  )
```

